name: itbee_interview
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  calendar_date_picker2: ^2.0.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_timezone: ^4.1.0
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  nested_scroll_view_plus: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  pull_to_refresh: ^2.0.0
  sqflite: ^2.4.2
  swipeable_page_route: ^0.4.7
  timezone: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.15
  easy_localization_generator:
    git:
      url: https://github.com/Danilz-2706/easy_localization_generator.git
      ref: v1.2
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/sounds/
    - assets/languages/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LexendExa
      fonts:
        - asset: assets/languages/LexendExa-VariableFont_wght.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
